Switch to iris3 (#819)
* Fix AttributeError: 'DimCoord' object has no attribute '_as_defn', use new attribute .metadata instead

* Replace .extract_strict -> .extract_cube

* Pin iris version to 3.0.1, because the changes are not backward compatible

* Fix tests failing with 'ValueError: Invalid units: sigma must be dimensionless.'

* Rename .coord_comparison -> ._dimensional_metadata_comparison

* Solve CoordinateNotFoundError in test

* Added automatic fix for invalid sigma units in AtmosphereSigmaFactory

* Try to avoid outdated pytest cache

* Fixed custom AtmosphereSigmaFactory

* unpin cftime

Co-authored-by: Valeriu Predoi <valeriu.predoi@gmail.com>
Co-authored-by: Javier Vegas-Regidor <javier.vegas@bsc.es>
Co-authored-by: Manuel Schlund <manuel.schlund@dlr.de>
Co-authored-by: Bouwe Andela <b.andela@esciencecenter.nl>